### PR TITLE
fix(extension-react-component): use Array.from for portals.entries()

### LINKED ISSUE #1700: TypeError e.portals.entries is not a function or its return value is not iterable
### Summary

TypeError
 
eval(/node_modules/@remirror/extension-react-component/dist/remirror-extension-react-component.browser.cjs.js)

### Steps to reproduce

This error occurs on Android devices 

Chrome Mobile
Version:102.0.0
Android
Version:10,11,12

Also valid issue for iPhone Chrome Mobile

### Trace

I tracked down to

https://github.com/remirror/remirror/blob/a2ca7a83f35b3831b97817eb2cb38b1a82d60ab8/packages/remirror__extension-react-component/src/portals/react-portals.tsx#L39

https://github.com/remirror/remirror/blob/a2ca7a83f35b3831b97817eb2cb38b1a82d60ab8/packages/remirror__react-core/src/react-remirror.tsx#L121

### PR DESCRIPTION
**Pull request by strdr4605**
Closes #1700

### Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [ ] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test extension-react-component`.

### CODE REVIEW

File: packages/remirror__extension-react-component/src/portals/react-portals.tsx [hunk 1]
```diff
@@ -36,13 +37,13 @@ export interface RemirrorPortalsProps {
  * passed through to the `RemirrorPortals` component.
  */
 export function usePortals(portalContainer: PortalContainer): Array<[HTMLElement, MountedPortal]> {
-  const [portals, setPortals] = useState(() => [...portalContainer.portals.entries()]);
+  const [portals, setPortals] = useState(() => Array.from(portalContainer.portals.entries()));
```
Comment (whawker) [inline packages/remirror__extension-react-component/src/portals/react-portals.tsx:40]: Good spot @strdr4605! 

If you don't mind, could you disable each line, rather than the entire file?

```suggestion
  // eslint-disable-next-line unicorn/prefer-spread
  const [portals, setPortals] = useState(() => Array.from(portalContainer.portals.entries()));
```
