### PR TITLE
fix(core-utils): `isNodeActive` now matches partial attributes

### LINKED ISSUE #385: Active state for headings not working when there are additional attributes
## Description

This might be what caused my issue with #379 🤔

I have an extension which appends a unique id to top-level blocks, something like:

```
<h1 id="unique-id-1>Hello!</h1>
<p id="unique-id-2>Some text here</p>
<ul id="unique-id-3">
  <li><p>Item</p></li>
  <li><p>Item</p></li>
</ul>
```

At this point, when triggering the menu for `<h1 id="unique-id-1>Hello!</h1>`, the active state for H1 is false.

It looks like [`isNodeActive`](https://github.com/remirror/remirror/blob/9dafc29cc7a70ec1c9e5cbd19091f27e20d7b035/packages/%40remirror/core-utils/src/prosemirror-utils.ts#L535-L549) returns `false` when there are extra `attrs` other than exactly `{ level: <number> }`; in my case, `{ id: <string>, level: <number> }`

**Returns `false` when there is an additional attribute, `id`:**

Screen Shot 2020-07-27 at 3 03 05 PM

**Returns `true` as expected when `level` is the only attribute:**

Screen Shot 2020-07-27 at 3 04 46 PM

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/HEAD/docs/contributing.md) document.

### PR DESCRIPTION
**Pull request by ifiokjr**
## Description

Closes #385 

## Checklist

- [x] I have read the [**contributing**](https://github.com/remirror/remirror/blob/master/docs/contributing.md) document.
- [x] My code follows the code style of this project and `pnpm fix` completed successfully.
- [x] I have updated the documentation where necessary.
- [x] New code is unit tested and all current tests pass when running `pnpm test`.

### CODE REVIEW

File: packages/@remirror/core-utils/src/prosemirror-utils.ts [hunk 1]
```diff
@@ -545,7 +545,7 @@ export function isNodeActive(parameter: IsNodeActiveParameter) {
     return bool(parent);
   }
 
-  return parent.node.hasMarkup(type, attrs);
+  return parent.node.hasMarkup(type, { ...parent.node.attrs, ...attrs });
```
Comment (tommoor) [inline packages/@remirror/core-utils/src/prosemirror-utils.ts:548]: Perfect 👌
